### ISSUE TITLE
Error: socket hang up

### ISSUE THREAD

**Issue by torfeld6** [james-proxy/james#369] opened 2018-03-09 15:30 UTC
We're all using macOS in my company and after three to five minutes of using james-proxy with https the following error occurs:

   Error: socket hang up
      at createHangUpError (_http_client.js:302:15)
      at Socket.socketOnEnd (_http_client.js:394:23)
      at emitNone (events.js:91:20)
      at Socket.emit (events.js:188:7)
      at endReadableNT (_stream_readable.js:975:12)
      at _combinedTickCallback (internal/process/next_tick.js:80:11)
      at process._tickDomainCallback (internal/process/next_tick.js:128:9)

Kind Regards
Joshua

**Comment by torfeld6** [comment] 2018-03-09 15:33
Additional Information: we're not using the browser links, but configured the proxy in the network settings.

![screen shot 2018-03-09 at 16 32 53](https://user-images.githubusercontent.com/661673/37215188-8f7b9310-23b7-11e8-9a0d-e3f8932c35c4.png)

**Comment by mitchhentges** [comment] 2018-03-09 16:05
Hey, thanks for the bug report - I think that's the same one as [we're seeing internally](https://sentry.fuzzlesoft.ca/share/issue/2d2e152440de4fdd855363a2726fc8e7/).

Two questions:
* Can you remember doing anything in particular to trigger this bug other than just using James for a couple minutes?
* Do you experience any bad behaviour when this bug occurs (I dunno, but maybe something like a request not showing up in James?)

**Comment by torfeld6** [comment] 2018-03-09 17:17
Hi there,

1. No, I don't. I was opening github.com when it crashed the last time (see log.txt for more information). Is there any other log file to help you?
2. I opened GitHub and there was no response for about 30 seconds before James crashed.

Kind Regards
Joshua

[log.txt](https://github.com/james-proxy/james/files/1797760/log.txt)

**Comment by mitchhentges** [comment] 2018-03-09 17:21
Oh jeez, it crashed? Sounds pretty serious.
That log file is super helpful, thanks.

I'll take a look when I've got some free time

**Comment by Defilan** [comment] 2018-05-01 21:03
Hey @torfeld6 and @mitchhentges , I just wanted to hop on and report that this exact same issue is happening on a Fedora 27 system too. 

`  Error: socket hang up
      at createHangUpError (_http_client.js:302:15)
      at Socket.socketOnEnd (_http_client.js:394:23)
      at emitNone (events.js:91:20)
      at Socket.emit (events.js:188:7)
      at endReadableNT (_stream_readable.js:975:12)
      at _combinedTickCallback (internal/process/next_tick.js:80:11)
      at process._tickDomainCallback (internal/process/next_tick.js:128:9)
`

Thanks!

**Comment by mitchhentges** [comment] 2018-09-14 07:05
Looking into this further, it seems like there's a very quick performance hit/leak once you visit more than a couple sites. My guess is that once the app hangs for long enough, whatever connection it was proxying gives up (and hangs up), and around that time the app crashes, too.

Ideally, by addressing the performance issues, this might be solved in the process

**Comment by nerdbeere** [comment] 2018-09-17 08:56
Also looked into this a bit and I found a fairly easy way to reproduce this:

1. Make sure https proxying works
2. Open a new browser (chrome in my case)
3. Open 30+ tabs of amazon
4. Wait for a minute or so until the crash occurs

Performance is really bad so I decided to basically disable everything that's going on in james except for the actual request interception by commenting out these lines: https://github.com/james-proxy/james/blob/master/src/main/proxy.js#L127-L129
This led to a significant boost in performance but the error still occurs.

The stacktrace suggests that this error happens when hoxy sends out the request. As it turns out hoxy [does not properly handle errors](https://github.com/greim/hoxy/pull/93#issuecomment-417692187).

My conclusion:
- James slows down proxy performance but it seems unrelated to the socket hang up error
- It's unclear to me _why_ this error occurs, maybe it's some sort of timeout
- [Hoxy needs proper](https://github.com/greim/hoxy/issues/60) [error handling](https://github.com/greim/hoxy/pull/93#issuecomment-417692187)

**Comment by nerdbeere** [comment] 2018-09-17 10:55
**Update:** https://github.com/james-proxy/hoxy/pull/1/files seems to fix the crash.

I changed 3 things:
1. Add error handling for http server
2. Add error handling for http client
3. End request as [suggested in the node docs](https://nodejs.org/api/http.html#http_http_request_options_callback)

**Comment by torfeld6** [comment] 2018-09-17 11:28
I'd like to test it, but I have no idea how to build James with the updated hoxy library. @nerdbeere is it possible to provide a macOS build?

**Comment by nerdbeere** [comment] 2018-09-17 11:45
> I'd like to test it, but I have no idea how to build James with the updated hoxy library. @nerdbeere is it possible to provide a macOS build?

@torfeld6 Here's a short how-to:

- Clone [https://github.com/james-proxy/hoxy]()
- Checkout branch `add-error-handling`
- `npm install`
- `npm run compile`
- `npm link`

Assuming that you also cloned the james repo and starting it with `npm run start`:
- Go to james project root
- `npm link hoxy`
- `npm start`

Explanation:
`npm link` allows you to link dependencies locally so you can work on dependencies without the need to publish every change to npm.

**Comment by nerdbeere** [comment] 2018-09-17 12:02
@mitchhentges assuming my fixes work, what do you think would be the best course of action? Should we try to get the fixes into hoxy or start using our own fork?
We still have open PRs there from 2016.

**Comment by mitchhentges** [comment] 2018-09-17 16:35
@nerdbeere you're on fire :100:
I think that we should create a PR into hoxy "upstream" (which will hopefully eventually be merged), but we should also publish our own fork - especially if the hoxy PR hasn't been merged for our next release, which should hopefully be soon considering some of the potential improvements in James :wink:

**Closed** 2018-09-19 06:47 UTC
