### ISSUE TITLE
In browser list, visualize which browsers can be proxied automatically

### ISSUE THREAD

**Issue by mitchhentges** [james-proxy/james#338] opened 2017-11-20 18:23 UTC
I've got no mockup designs in mind, but just something to think about:
Chrome and Firefox can be launched from James so that they create a new window that strictly throws requests through James without the user having to adjust any settings.
Other browsers, like IE (and ... Safari? I can't remember) don't have a programmatic way of adjusting the proxy.
We should have some kind of distinction in the browser list for browsers that proxy nicely when clicked

**Comment by nerdbeere** [comment] 2017-11-22 12:53
Maybe we should just show chrome and firefox and add a small text that says something like "we also detected browserX and browserY but you need to configure them manually".
It's kind of confusing if you click on IE and it works but requests don't show up in james.

**Comment by tomitm** [comment] 2017-12-30 00:40
This seems like a dupe of #333?

**Comment by mitchhentges** [comment] 2017-12-30 01:11
Good catch, I'm blind

**Closed** 2017-12-30 01:10 UTC
